import type { ResumeInput } from "@profile/schema";

export function buildAdvisorPrompt(resume: ResumeInput): string {
  const skills = resume.skills.map((s) => s.label).join(", ");
  const projects = resume.projects.map((p) => `${p.name}: ${p.tagline.en}`).join("; ");
  return [
    `You are a senior tech career advisor. Analyze this profile for ${resume.person.name}.`,
    `Current title: ${resume.person.title.en}. Location: ${resume.person.location}.`,
    `Skills: ${skills}.`,
    `Projects: ${projects}.`,
    `Produce four clearly separated sections:`,
    `1. Matching current job openings (roles + why they fit).`,
    `2. Skill gaps to close (concrete, prioritized).`,
    `3. Positioning strategies (how to sell the profile better).`,
    `4. CV/UX improvement ideas for an API-first web resume.`,
    `Be specific and actionable. Return Markdown with a "## " heading per section.`,
  ].join("\n");
}

export function renderInsights(sections: { title: string; body: string }[]): string {
  const header = `# Career Insights\n\n> Generated by scripts/career-advisor.ts — private, do not commit.\n`;
  return header + "\n" + sections.map((s) => `## ${s.title}\n\n${s.body}`).join("\n\n") + "\n";
}
